version: '2'
services:
  web:
    build:
      image: rotati/grapeapi-example
      dockerfile: Dockerfile
    environment:
      TEST_TOKEN: Testing123
    volumes:
      - .:/app
    cached: true
  awsdeployment:
    image: codeship/aws-deployment
    encrypted_env_file: aws-deployment.env.encrypted
    environment:
      - AWS_DEFAULT_REGION=ca-central-1
    volumes:
      - ./:/deploy
